name: mdlm_loo
backbone: dit  # dit / dimamba / hf_dit
parameterization: subs
time_conditioning: False
T: 0  # 0 (continuous time) / 1000 
subs_masking: False
causal_attention: False
num_segments: 8
num_loo: 3
guidance_factor: 1.0
ignore_bos: False
loss_type: elbo
